print("False and False == " + str(False and False))
print("False and True == " + str(False and True))
print("True and False == " + str(True and False))
print("True and True == " + str(True and True) + '\n')

print("False or False == " + str(False or False))
print("False or True == " + str(False or True))
print("True or False == " + str(True or False))
print("True or True == " + str(True or True) + '\n')

print("not False == " + str(not False))
print("not True == " + str(not True) + '\n')

print("not(False and False) == " + str(not(False and False)))
print("not(False and True) == " + str(not(False and True)))
print("not(True and False) == " + str(not(True and False)))
print("not(True and True) == " + str(not(True and True)) + '\n')

print("not(False or False) == " + str(not(False or False)))
print("not(False or True) == " + str(not(False or True)))
print("not(True or False) == " + str(not(True or False)))
print("not(True or True) == " + str(not(True or True)) + '\n')

print("12 == 12: " + str(12 == 12))
print("12 != 2: " + str(12 != 2))
print("12 > 2: " + str(12 > 2))
print("12 >= 12: " + str(12 >= 12))
print("2 < 12: " + str(2 < 12))
print("12 <= 12: " + str(12 <= 12) + '\n')

print("12 == 2: " + str(12 == 2))
print("12 != 12: " + str(12 != 12))
print("12 > 12: " + str(12 > 12))
print("2 >= 12: " + str(2 >= 12))
print("12 < 12: " + str(12 < 12))
print("12 <= 2: " + str(12 <= 2) + '\n')

print("not(12 == 12): " + str(not(12 == 12)))
print("not(12 != 2): " + str(not(12 != 2)))
print("not(12 > 2): " + str(not(12 > 2)))
print("not(12 >= 12): " + str(not(12 >= 12)))
print("not(2 < 12): " + str(not(2 < 12)))
print("not(12 <= 12): " + str(not(12 <= 12)) + '\n')

print("not(12 == 2): " + str(not(12 == 2)))
print("not(12 != 12): " + str(not(12 != 12)))
print("not(12 > 12): " + str(not(12 > 12)))
print("not(2 >= 12): " + str(not(2 >= 12)))
print("not(12 < 12): " + str(not(12 < 12)))
print("not(12 <= 2): " + str(not(12 <= 2)) + '\n')
